%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 501.4757919305817
Camera.fy: 501.4757919305817
Camera.cx: 421.7953735163109
Camera.cy: 167.65799492501083

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 800
Camera.height: 400

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
Camera.bf: 150.691550759

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Transformation from body-frame (imu) to rectified left camera
#
# This is the transform with respect to the non-rectified image.
# Actually it should be correct to define it with respect to the rectified image,
# however, then results get worse.
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.9998852242642406, -0.013522961078544133, 0.006831385051241187, 0.17541216744862287,
          -0.006890161859766396, 0.004304637029338462, -0.9999669973402087, 0.0036894333751345677, 
           0.01349310815180704, -0.9998992947410829, -0.004397318352110671, -0.05810612695941222,
           0.0, 0.0, 0.0, 1.0]

# IMU noise (probably not optimal paramters)
IMU.NoiseGyro: 0.0014 # rad/s^0.5 
IMU.NoiseAcc: 0.006 # m/s^1.5
IMU.GyroWalk: 0.0001 # rad/s^1.5
IMU.AccWalk: 0.0001 # m/s^2.5
IMU.Frequency: 2000

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000
