%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 527.9990706330082
Camera.fy: 527.963495807245
Camera.cx: 399.18451401412665
Camera.cy: 172.8193108347693

# Kannala-Brandt distortion parameters
Camera.k1: -0.0355976
Camera.k2: -0.00509372
Camera.k3: 0.01971628
Camera.k4: -0.0158328

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 529.2496538273606
Camera2.fy: 529.4013679656194
Camera2.cx: 412.4733148308946
Camera2.cy: 172.1405434152354

# Kannala-Brandt distortion parameters
Camera2.k1: -0.03696482
Camera2.k2: 0.01024009
Camera2.k3: -0.01632903
Camera2.k4: 0.00959772
    
# Transformation matrix from right camera to left camera
Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [ 0.999867211, -0.00960388430, 0.0131653238, 0.300414532,
          0.00959188638, 0.999953522, 0.000974169004, 0.00259197715,
         -0.0131740678, -0.000847759355, 0.999912859, -0.00733712726]

# Lapping area between images
Camera.lappingBegin: 0
Camera.lappingEnd: 511

Camera2.lappingBegin: 0
Camera2.lappingEnd: 511

# Camera resolution
Camera.width: 800
Camera.height: 400

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0
Camera.bf: 150.691550759


# Transformation from body-frame (imu) to left camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.9998852242642406, -0.013522961078544133, 0.006831385051241187, 0.17541216744862287,
          -0.006890161859766396, 0.004304637029338462, -0.9999669973402087, 0.0036894333751345677, 
           0.01349310815180704, -0.9998992947410829, -0.004397318352110671, -0.05810612695941222,
           0.0, 0.0, 0.0, 1.0]

# IMU noise (probably not optimal paramters)
IMU.NoiseGyro: 0.0014 # rad/s^0.5 
IMU.NoiseAcc: 0.006 # m/s^1.5
IMU.GyroWalk: 0.0001 # rad/s^1.5
IMU.AccWalk: 0.0001 # m/s^2.5
IMU.Frequency: 2000

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20 # 20
ORBextractor.minThFAST: 7 # 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500
